name: App test and production deployment

on:
  push:
    paths:
      - "app/**"
    branches:
      - "main"

jobs:
  validate:
    uses: dsaltares/invoicing/.github/workflows/app-shared.yml@main

  deployVercel:
    runs-on: ubuntu-latest
    needs: [validate]
    steps:
      - uses: actions/checkout@v2
      - uses: amondnet/vercel-action@v20
        with:
          vercel-args: '--prod'
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-project-name: ${{ secrets.VERCEL_PROJECT_NAME}}
          scope: ${{ secrets.VERCEL_ORG_ID}}
